# Generated by Django 4.2.2 on 2023-07-01 12:55

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('due_date', models.DateField(default=datetime.datetime(2023, 7, 1, 12, 55, 0, 628725))),
                ('description', models.TextField()),
            ],
        ),
    ]
