# Generated by Django 4.2.5 on 2023-09-20 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 13, 10, 20, 158425, tzinfo=datetime.timezone.utc)),
        ),
    ]
