# Generated by Django 4.2.1 on 2023-09-20 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 17, 22, 35, 587160, tzinfo=datetime.timezone.utc)),
        ),
    ]
