# Generated by Django 4.2.1 on 2023-09-09 13:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Enter business email', max_length=254)),
                ('phone', models.IntegerField(help_text='Enter business phone number')),
                ('message', models.TextField(blank=True, help_text='leave a brief message for clients', null=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name your savings goal.', max_length=100)),
                ('goal', models.IntegerField(help_text='Savings Goal')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(default=datetime.datetime(2023, 9, 9, 13, 46, 24, 961932, tzinfo=datetime.timezone.utc), help_text="When do you want to reach your saving's goal?")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter debt type or bill type', max_length=200)),
                ('amount', models.IntegerField(help_text='enter amount owed')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(default=datetime.datetime(2023, 9, 9, 13, 46, 24, 918071, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Use the tab keys for quick completion.', max_length=100)),
                ('expenses', models.IntegerField(help_text='Enter  0 if recording income')),
                ('income', models.IntegerField(help_text='Enter 0 if recording an expense')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('is_monthly', models.BooleanField(default=False, help_text='Is this income/expense a weekly fixed or one time event?')),
                ('is_weekly', models.BooleanField(default=False, help_text='Is this income/expense a weekly fixed or one time event?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
