# Generated by Django 4.2.5 on 2023-09-20 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_debt_deadline_alter_savingsgoal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2023, 9, 20, 13, 10, 20, 160901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2023, 9, 20, 13, 10, 20, 161324, tzinfo=datetime.timezone.utc), help_text="When do you want to reach your saving's goal?"),
        ),
    ]
